sudo: false
cache: bundler
language: ruby

rvm:
#  - 2.0
  - 2.1
  - 2.2

bundler_args: --jobs 7 --retry 3

gemfile:
#  - Gemfile
  - gemfile.travis

env:
  - CHEF_VERSION=master
#  - CHEF_VERSION=12.4.1
#  - CHEF_VERSION=12.4.0
#  - CHEF_VERSION=12.3.0
#  - CHEF_VERSION=12.2.1
#  - CHEF_VERSION=12.1.2
#  - CHEF_VERSION=12.1.1
#  - CHEF_VERSION=12.1.0
#  - CHEF_VERSION=12.0.3
#  - CHEF_VERSION=11.18.6
#  - CHEF_VERSION=11.18.0
#  - CHEF_VERSION=11.16.4
#  - CHEF_VERSION=11.16.2
#  - CHEF_VERSION=11.16.0
#  - CHEF_VERSION=11.14.6
#  - CHEF_VERSION=11.14.2

matrix:
  fast_finish: true
  allow_failures:
    - env: CHEF_VERSION=master

script:
  - bundle exec foodcritic -f any
